name: Guarana
version: 0.95dev
date: 2012-04-27
description: |
    Applications of Lie methods for computations with infinite polycyclic  groups

authors:
    - name: Bjoern Assmann
      url: mailto:bjoern@mcs.st-and.ac.uk

contributors:
    - name: John McDermott
      url: mailto:jjm@mcs.st-and.ac.uk

GAP: ">= 4.7"

needed-pkgs:
    - name: "gapdoc"
      version: ">=1.3"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "polycyclic"
      version: ">=1.1"
      url: "https://gap-packages.github.io/polycyclic/"
    - name: "polenta"
      version: ">=1.2.3"
      url: "https://gap-packages.github.io/polenta/"

suggested-pkgs:
    - name: "nq"
      version: ">=2.0"
      url: "http://gap-packages.github.io/nq/"
    - name: "alnuth"
      version: ">=3.0.0"
      url: "https://gap-packages.github.io/alnuth"

www: http://www-circa.mcs.st-andrews.ac.uk/~jjm/software/Guarana
readme: README
packageinfo: http://www-circa.mcs.st-andrews.ac.uk/~jjm/software/Guarana/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://www-circa.mcs.st-andrews.ac.uk/~jjm/software/Guarana/Guarana-0.95dev.tar.gz

abstract: |
    The Guarana package provides computational applications of the Mal'cev correspondence, in particular for collection in infinite polycyclic groups.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    GitHub Pages, GAP.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>HTI17</span>]   <b class='BibAuthor'>Horn, M., Thor, A. U. and Itor, J.</b>,
     <i class='BibTitle'>GitHubPagesForGAP, A GitHub Pages generator for GAP packages,
             Version 0.2</i>
     (<span class='BibYear'>2017</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-system.github.io/GitHubPagesForGAP/">https://gap-system.github.io/GitHubPagesForGAP/</a></span>.
    </p>
    

bibtex: |
    @misc{ GitHubPagesForGAP0.2,
      author =           {Horn, M. and Thor, A. U. and Itor, J.},
      title =            {{GitHubPagesForGAP}, A GitHub Pages generator for GAP packages, {V}ersion 0.2},
      month =            {Feb},
      year =             {2017},
      note =             {GAP package},
      howpublished =     {\href                              {https://gap-system.github.io/GitHubPagesForGAP/}
                          {\texttt{https://gap-system.github.io/}\discretionary
                          {}{}{}\texttt{GitHubPagesForGAP/}}},
      keywords =         {GitHub Pages; GAP},
      printedkey =       {HTI17}
    }

